# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: "Test Python code"
description: "Install Python and run tests"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: "pip"

    - run: pip install -r requirements_test.txt
      shell: sh

    - run: pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
      shell: sh

    - run: ruff format --check .
      shell: sh

    - run: ruff check .
      shell: sh
