[tool.ruff]
line-length = 88

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 88

[tool.ruff.lint]
select = [
    "E",
    "W",
    "F",
    "N",
    "UP",
    "I",
    "ASYNC",
    "S",
    "FBT",
    "B",
    "A",
    "COM",
    "C4",
    "DTZ",
    "EM",
    "ISC",
    "ICN",
    "G",
    "INP",
    "PIE",
    "T20",
    "Q",
    "RSE",
    "RET",
    "SLF",
    "TCH",
    "ARG",
    "PTH",
    "ERA",
    "PL",
    "TRY",
    "PERF",
    "LOG",
    "I001",
    "C90",
    "SIM",
    "RUF",
    "PT",
]
ignore = [
    "PLR2004", # asks to change every value comparisons with constants, overkill
    "SIM108",  # converts all if-else assignments to ternary, this is not always more readable
    # conflict with ruff format
    "COM812",
    "ISC001",
    "RET504", # I like assigning to variables before returning so I can add breakpoints
]

[tool.ruff.lint.per-file-ignores]
"tests.py" = ["S101"]
